### ISSUE TITLE
Records dropped from data stream

### ISSUE THREAD

**Issue by labutler** [opensensorhub/osh-core#63] opened 2017-04-13 15:33 UTC
I'm working on the USGS water data driver. Single outputs are working ok, except when two like measurements come from the same site together (rare, but I've seen it happen with sites in Alaska). This seems to be related to the same problem we're having below for DataChoice. As you can see below, if say there is a measurement of Discharge and Gage Height coming from the same site in sequence, then one of the measurements is dropped. This seems to happen in the publishEvent() method. Perhaps due to trying to avoid duplicate events.

    public void publishData(List<USGSDataRecord> dataRec)
    {
    	DataBlock dataBlock;
    	int count = 0;
    	for (USGSDataRecord rec : dataRec)
    	{
    		dataChoice.setSelectedItem(getItemName(rec.getDataType()));
        	dataBlock = dataChoice.createDataBlock();
        	
    		int blockPos = 1;
    		dataBlock.setDoubleValue(blockPos++, rec.getTimeStamp()/1000);
    		dataBlock.setStringValue(blockPos++, rec.getSiteCode());
    		dataBlock.setDoubleValue(blockPos++, rec.getSiteLat());
    		dataBlock.setDoubleValue(blockPos++, rec.getSiteLon());
    		dataBlock.setFloatValue(blockPos++, rec.getDataValue());
    		
			System.out.println(rec.getDataType() + "," + rec.getTimeStamp() + "," + rec.getSiteCode() + "," + rec.getSiteLat() + "," + rec.getSiteLon() + "," + rec.getDataValue());
			
			
    		latestRecordTime = System.currentTimeMillis();
    		latestRecord = dataBlock;
    		latestRecords.put(rec.getSiteCode(), latestRecord); 
    		eventHandler.publishEvent(new SensorDataEvent(latestRecordTime, rec.getSiteCode(), AllWaterOutput.this, dataBlock));
    		count++;
    	}
    	System.out.println("published " + count + " records");
    }

From Driver Printout (before publishEvent):
Discharge,1222847100000,15087618,57.12491678,-135.3334277,48.0
Discharge,1253691900000,15861000,70.2201986,-151.8378484,106.0
Gage Height,1254383100000,15861000,70.2201986,-151.8378484,20.6
Discharge,1372319100000,15285000,61.64307278,-149.1983305,15.0
Gage Height,1372381200000,15285000,61.64307278,-149.1983305,7.75
Discharge,1412149500000,15291000,63.10343837,-147.5180902,2090.0
Gage Height,1412149500000,15291000,63.10343837,-147.5180902,8.62
Water Temperature,1412149500000,15291000,63.10343837,-147.5180902,0.0
Water Temperature,1413615600000,15302300,59.8376227,-156.6938693,2.0
Discharge,1413618300000,15302300,59.8376227,-156.6938693,5470.0
Discharge,1413618300000,15302320,59.80901149,-156.6669229,445.0
Water Temperature,1413618300000,15302320,59.80901149,-156.6669229,2.3
Gage Height,1413657000000,15302320,59.80901149,-156.6669229,18.44
Gage Height,1413663300000,15302300,59.8376227,-156.6938693,10.97
Discharge,1413704700000,15301500,60.1539944,-158.7366923,858.0
Gage Height,1413752400000,15301500,60.1539944,-158.7366923,11.08
Water Temperature,1430556300000,15129120,59.19026419,-138.3284089,0.5
Discharge,1443037500000,15515080,64.01121149,-148.727612,4.5
Discharge,1444290300000,15302200,59.7926376,-155.5246895,516.0
Gage Height,1444333500000,15302200,59.7926376,-155.5246895,18.88
Discharge,1452069900000,15100000,57.1427162,-134.8656418,46.0
Gage Height,1452112200000,15100000,57.1427162,-134.8656418,16.91
Water Temperature,1473234300000,15896000,70.28138539,-148.962786,3.9
Water Temperature,1473320700000,15908000,69.0158333,-148.8177778,2.5

From SOS Request:
Discharge,2008-10-01T07:45:00Z,15087618,57.12491678,-135.3334277,48.0
GageHeight,2009-10-01T07:45:00Z,15861000,70.2201986,-151.8378484,20.600000381469727
GageHeight,2013-06-28T01:00:00Z,15285000,61.64307278,-149.1983305,7.75
WaterTemperature,2014-10-01T07:45:00Z,15291000,63.10343837,-147.5180902,0.0
GageHeight,2014-10-18T20:15:00Z,15302300,59.8376227,-156.6938693,10.970000267028809
GageHeight,2014-10-18T18:30:00Z,15302320,59.80901149,-156.6669229,18.440000534057617
GageHeight,2014-10-19T21:00:00Z,15301500,60.1539944,-158.7366923,11.079999923706055
GageHeight,2017-04-12T21:45:00Z,15129120,59.19026419,-138.3284089,7.489999771118164
Discharge,2015-09-23T19:45:00Z,15515080,64.01121149,-148.727612,4.5
GageHeight,2015-10-08T19:45:00Z,15302200,59.7926376,-155.5246895,18.8799991607666
GageHeight,2016-01-06T20:30:00Z,15100000,57.1427162,-134.8656418,16.90999984741211
WaterTemperature,2016-09-07T07:45:00Z,15896000,70.28138539,-148.962786,3.9000000953674316
WaterTemperature,2016-09-08T07:45:00Z,15908000,69.0158333,-148.8177778,2.5
GageHeight,2016-10-05T21:45:00Z,15292400,62.55810837,-150.23616,3.4800000190734863
WaterTemperature,2016-09-29T07:45:00Z,15348000,64.3088552,-141.4045168,1.7999999523162842
GageHeight,2016-11-05T13:00:00Z,15457790,65.57540267,-148.3911245,44.16999816894531
GageHeight,2016-10-12T00:15:00Z,15300250,59.7859761,-155.2552406,17.25
WaterTemperature,2016-10-12T21:30:00Z,15260001,60.43441667,-149.8245278,7.400000095367432
GageHeight,2016-10-26T22:00:00Z,15493400,64.8595879,-146.8057505,12.59000015258789
GageHeight,2016-10-15T07:45:00Z,15281000,61.5044605,-149.032765,6.130000114440918
WaterTemperature,2016-12-04T08:45:00Z,15564879,67.25429,-150.1760612,0.0
WaterTemperature,2016-12-12T08:45:00Z,15293700,61.80974586,-150.0972379,0.0
WaterTemperature,2016-12-15T08:45:00Z,15803000,70.4953764,-157.395848,0.0
GageHeight,2017-02-23T23:00:00Z,15072000,55.3916038,-131.1955833,1.4199999570846558
GageHeight,2017-02-21T19:00:00Z,15101490,58.08299837,-134.6334448,1.6200000047683716
GageHeight,2017-03-24T13:30:00Z,15052000,58.3913429,-134.4226062,6.570000171661377
GageHeight,2017-04-12T21:15:00Z,15200280,62.5203918,-145.5330154,7.420000076293945
GageHeight,2017-04-12T15:45:00Z,15008000,56.025815,-130.0669823,17.030000686645508
GageHeight,2017-04-12T21:30:00Z,15081497,55.8010287,-133.1103222,7.690000057220459
GageHeight,2017-04-12T21:30:00Z,15239070,59.80107399,-150.8849079,5.010000228881836
GageHeight,2017-04-12T21:15:00Z,15290000,61.7097433,-149.231938,1.5700000524520874

**Comment by alexrobin** [comment] 2019-10-31 15:23
Closing as I was not able to reproduce. This may have been fixed in later releases.

**Closed by alexrobin** 2019-10-31 15:23 UTC
