### ISSUE TITLE
AdminUI - right panel doesn't change with "menu" selection

### ISSUE THREAD

**Issue by mikebotts** [opensensorhub/osh-core#77] opened 2017-06-12 20:09 UTC
Tested on http://botts-geo.com:8282/sensorhub/admin

When one changes from say "Sensors" to "Storage"  or "Services" or whatever, the right panel doesn't change to reflect the menu change but keeps the previous panel displayed. Perhaps it should display whatever module is currently selected in the new category (in blue) or display "No Storage Modules" enabled or whatever is appropriate for that menu selection.

Related to Issue #67 and possibly #68.

**Comment by alexrobin** [comment] 2017-06-12 20:11
Duplicate of #68 (which is fixed in 1.3 branch)

**Closed by alexrobin** 2017-06-12 20:11 UTC
Labels: duplicate
